// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdIwKt8KJ5vMgWKMFFWwa_Au1vAlV9kU',
    appId: '1:745234518617:web:b5d67814f400b902301748',
    messagingSenderId: '745234518617',
    projectId: 'online-ordering-system-7239a',
    authDomain: 'online-ordering-system-7239a.firebaseapp.com',
    storageBucket: 'online-ordering-system-7239a.appspot.com',
    measurementId: 'G-DJX6CVWEEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZxKIAr5RFitTieDhgByZFLg2NRe0_xw',
    appId: '1:745234518617:android:8c10bdb2326af4f8301748',
    messagingSenderId: '745234518617',
    projectId: 'online-ordering-system-7239a',
    storageBucket: 'online-ordering-system-7239a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCev1DSHHpsdI7ClmW9OHfNe19B-O56Lxk',
    appId: '1:745234518617:ios:ff6c571c7937839b301748',
    messagingSenderId: '745234518617',
    projectId: 'online-ordering-system-7239a',
    storageBucket: 'online-ordering-system-7239a.appspot.com',
    iosClientId: '745234518617-0mpino2ua0g3r8ah36st3bc9o9dufmlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineOrderingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCev1DSHHpsdI7ClmW9OHfNe19B-O56Lxk',
    appId: '1:745234518617:ios:ff6c571c7937839b301748',
    messagingSenderId: '745234518617',
    projectId: 'online-ordering-system-7239a',
    storageBucket: 'online-ordering-system-7239a.appspot.com',
    iosClientId: '745234518617-0mpino2ua0g3r8ah36st3bc9o9dufmlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineOrderingSystem',
  );
}
